from typing import List, Tuple
pokemon_db: List[Tuple[str, str, int, List[str]]] = [
    (
        "Bulbasaur",  # name
        "Grass/Poison",  # type
        318,  # total
        [
            "HP: 45",
            "Attack: 49",
            "Defense: 49",
            "Sp. Atk: 65",
            "Sp. Def: 65",
            "Speed: 45",
        ],
    ),
    (
        "Ivysaur",
        "Grass/Poison",
        405,
        [
            "HP: 60",
            "Attack: 62",
            "Defense: 63",
            "Sp. Atk: 80",
            "Sp. Def: 80",
            "Speed: 60",
        ]
    ),
    (
        "Venusaur",
        "Grass/Poison",
        525,
        [
            "HP: 80",
            "Attack: 82",
            "Defense: 83",
            "Sp. Atk: 100",
            "Sp. Def: 100",
            "Speed: 80",
        ],
    ),
    (
        "Charmander",
        "Fire",
        309,
        [
            "HP: 39",
            "Attack: 52",
            "Defense: 43",
            "Sp. Atk: 60",
            "Sp. Def: 50",
            "Speed: 65",
        ],
    ),
    (
        "Charmeleon",
        "Fire",
        405,
        [
            "HP: 58",
            "Attack: 64",
            "Defense: 58",
            "Sp. Atk: 80",
            "Sp. Def: 65",
            "Speed: 80",
        ],
    ),
    (
        "Charizard",
        "Fire/Flying",
        534,
        [
            "HP: 78",
            "Attack: 84",
            "Defense: 78",
            "Sp. Atk: 109",
            "Sp. Def: 85",
            "Speed: 100",
        ],
    ),
    (
        "Squirtle",
        "Water",
        314,
        [
            "HP: 44",
            "Attack: 48",
            "Defense: 65",
            "Sp. Atk: 50",
            "Sp. Def: 64",
            "Speed: 43",
        ],
    ),
    (
        "Wartortle",
        "Water",
        405,
        [
            "HP: 59",
            "Attack: 63",
            "Defense: 80",
            "Sp. Atk: 65",
            "Sp. Def: 80",
            "Speed: 58",
        ],
    ),
    (
        "Blastoise",
        "Water",
        530,
        [
            "HP: 79",
            "Attack: 83",
            "Defense: 100",
            "Sp. Atk: 85",
            "Sp. Def: 105",
            "Speed: 78",
        ],
    ),
    (
        "Caterpie",
        "Bug",
        195,
        [
            "HP: 45",
            "Attack: 30",
            "Defense: 35",
            "Sp. Atk: 20",
            "Sp. Def: 20",
            "Speed: 45",
        ],
    ),
    (
        "Metapod",
        "Bug",
        205,
        [
            "HP: 50",
            "Attack: 20",
            "Defense: 55",
            "Sp. Atk: 25",
            "Sp. Def: 25",
            "Speed: 30",
        ],
    ),
    (
        "Butterfree",
        "Bug/Flying",
        395,
        [
            "HP: 60",
            "Attack: 45",
            "Defense: 50",
            "Sp. Atk: 90",
            "Sp. Def: 80",
            "Speed: 70",
        ],
    ),
    (
        "Weedle",
        "Bug/Poison",
        195,
        [
            "HP: 40",
            "Attack: 35",
            "Defense: 30",
            "Sp. Atk: 20",
            "Sp. Def: 20",
            "Speed: 50",
        ],
    ),
    (
        "Kakuna",
        "Bug/Poison",
        205,
        [
            "HP: 45",
            "Attack: 25",
            "Defense: 50",
            "Sp. Atk: 25",
            "Sp. Def: 25",
            "Speed: 35",
        ],
    ),
    (
        "Beedrill",
        "Bug/Poison",
        395,
        [
            "HP: 65",
            "Attack: 90",
            "Defense: 40",
            "Sp. Atk: 45",
            "Sp. Def: 80",
            "Speed: 75",
        ],
    ),
    (
        "Pidgey",
        "Normal/Flying",
        251,
        [
            "HP: 40",
            "Attack: 45",
            "Defense: 40",
            "Sp. Atk: 35",
            "Sp. Def: 35",
            "Speed: 56",
        ],
    ),
    (
        "Pidgeotto",
        "Normal/Flying",
        349,
        [
            "HP: 63",
            "Attack: 60",
            "Defense: 55",
            "Sp. Atk: 50",
            "Sp. Def: 50",
            "Speed: 71",
        ],
    ),
    (
        "Pidgeot",
        "Normal/Flying",
        479,
        [
            "HP: 83",
            "Attack: 80",
            "Defense: 75",
            "Sp. Atk: 70",
            "Sp. Def: 70",
            "Speed: 101",
        ],
    ),
    (
        "Rattata",
        "Normal",
        253,
        [
            "HP: 30",
            "Attack: 56",
            "Defense: 35",
            "Sp. Atk: 25",
            "Sp. Def: 35",
            "Speed: 72",
        ],
    ),
    (
        "Raticate",
        "Normal",
        413,
        [
            "HP: 55",
            "Attack: 81",
            "Defense: 60",
            "Sp. Atk: 50",
            "Sp. Def: 70",
            "Speed: 97",
        ],
    ),
    (
        "Spearow",
        "Normal/Flying",
        262,
        [
            "HP: 40",
            "Attack: 60",
            "Defense: 30",
            "Sp. Atk: 31",
            "Sp. Def: 31",
            "Speed: 70",
        ],
    ),
    (
        "Fearow",
        "Normal/Flying",
        442,
        [
            "HP: 65",
            "Attack: 90",
            "Defense: 65",
            "Sp. Atk: 61",
            "Sp. Def: 61",
            "Speed: 100",
        ],
    ),
    (
        "Ekans",
        "Poison",
        288,
        [
            "HP: 35",
            "Attack: 60",
            "Defense: 44",
            "Sp. Atk: 40",
            "Sp. Def: 54",
            "Speed: 55",
        ],
    ),
    (
        "Arbok",
        "Poison",
        448,
        [
            "HP: 60",
            "Attack: 95",
            "Defense: 69",
            "Sp. Atk: 65",
            "Sp. Def: 79",
            "Speed: 80",
        ],
    ),
    (
        "Pikachu",
        "Electric",
        320,
        [
            "HP: 35",
            "Attack: 55",
            "Defense: 40",
            "Sp. Atk: 50",
            "Sp. Def: 50",
            "Speed: 90",
        ],
    ),
    (
        "Raichu",
        "Electric",
        485,
        [
            "HP: 60",
            "Attack: 90",
            "Defense: 55",
            "Sp. Atk: 90",
            "Sp. Def: 80",
            "Speed: 110",
        ],
    ),
    (
        "Sandshrew",
        "Ground",
        300,
        [
            "HP: 50",
            "Attack: 75",
            "Defense: 85",
            "Sp. Atk: 20",
            "Sp. Def: 30",
            "Speed: 40",
        ],
    ),
    (
        "Sandslash",
        "Ground",
        450,
        [
            "HP: 75",
            "Attack: 100",
            "Defense: 110",
            "Sp. Atk: 45",
            "Sp. Def: 55",
            "Speed: 65",
        ],
    ),
    (
        "Nidoran Female",
        "Poison",
        275,
        [
            "HP: 55",
            "Attack: 47",
            "Defense: 52",
            "Sp. Atk: 40",
            "Sp. Def: 40",
            "Speed: 41",
        ],
    ),
    (
        "Nidorina",
        "Poison",
        365,
        [
            "HP: 70",
            "Attack: 62",
            "Defense: 67",
            "Sp. Atk: 55",
            "Sp. Def: 55",
            "Speed: 56",
        ],
    ),
    (
        "Nidoqueen",
        "Poison/Ground",
        505,
        [
            "HP: 90",
            "Attack: 92",
            "Defense: 87",
            "Sp. Atk: 75",
            "Sp. Def: 85",
            "Speed: 76",
        ],
    ),
    (
        "Nidoran Male",
        "Poison",
        273,
        [
            "HP: 46",
            "Attack: 57",
            "Defense: 40",
            "Sp. Atk: 40",
            "Sp. Def: 40",
            "Speed: 50",
        ],
    ),
    (
        "Nidorino",
        "Poison",
        365,
        [
            "HP: 61",
            "Attack: 72",
            "Defense: 57",
            "Sp. Atk: 55",
            "Sp. Def: 55",
            "Speed: 65",
        ],
    ),
    (
        "Nidoking",
        "Poison/Ground",
        505,
        [
            "HP: 81",
            "Attack: 102",
            "Defense: 77",
            "Sp. Atk: 85",
            "Sp. Def: 75",
            "Speed: 70",
        ],
    ),
    (
        "Clefairy",
        "Fairy",
        323,
        [
            "HP: 70",
            "Attack: 45",
            "Defense: 48",
            "Sp. Atk: 60",
            "Sp. Def: 65",
            "Speed: 35",
        ],
    ),
    (
        "Clefable",
        "Fairy",
        483,
        [
            "HP: 95",
            "Attack: 70",
            "Defense: 73",
            "Sp. Atk: 95",
            "Sp. Def: 90",
            "Speed: 60",
        ],
    ),
    (
        "Vulpix",
        "Fire",
        299,
        [
            "HP: 38",
            "Attack: 41",
            "Defense: 40",
            "Sp. Atk: 50",
            "Sp. Def: 65",
            "Speed: 65",
        ],
    ),
    (
        "Ninetales",
        "Fire",
        505,
        [
            "HP: 73",
            "Attack: 76",
            "Defense: 75",
            "Sp. Atk: 81",
            "Sp. Def: 100",
            "Speed: 100",
        ],
    ),
    (
        "Jigglypuff",
        "Normal/Fairy",
        270,
        [
            "HP: 115",
            "Attack: 45",
            "Defense: 50",
            "Sp. Atk: 28",
            "Sp. Def: 31",
            "Speed: 20",
        ],
    ),
    (
        "Wigglytuff",
        "Normal/Fairy",
        400,
        [
            "HP: 140",
            "Attack: 70",
            "Defense: 45",
            "Sp. Atk: 50",
            "Sp. Def: 50",
            "Speed: 45",
        ],
    ),
    (
        "Zubat",
        "Poison/Flying",
        245,
        [
            "HP: 40",
            "Attack: 45",
            "Defense: 40",
            "Sp. Atk: 30",
            "Sp. Def: 40",
            "Speed: 55",
        ],
    ),
    (
        "Golbat",
        "Poison/Flying",
        455,
        [
            "HP: 75",
            "Attack: 80",
            "Defense: 70",
            "Sp. Atk: 65",
            "Sp. Def: 75",
            "Speed: 90",
        ],
    ),
    (
        "Oddish",
        "Grass/Poison",
        320,
        [
            "HP: 45",
            "Attack: 50",
            "Defense: 55",
            "Sp. Atk: 75",
            "Sp. Def: 65",
            "Speed: 30",
        ],
    ),
    (
        "Gloom",
        "Grass/Poison",
        395,
        [
            "HP: 60",
            "Attack: 65",
            "Defense: 70",
            "Sp. Atk: 85",
            "Sp. Def: 75",
            "Speed: 40",
        ],
    ),
    (
        "Vileplume",
        "Grass/Poison",
        490,
        [
            "HP: 75",
            "Attack: 80",
            "Defense: 85",
            "Sp. Atk: 110",
            "Sp. Def: 90",
            "Speed: 50",
        ],
    ),
    (
        "Paras",
        "Bug/Grass",
        285,
        [
            "HP: 35",
            "Attack: 70",
            "Defense: 55",
            "Sp. Atk: 45",
            "Sp. Def: 55",
            "Speed: 25",
        ],
    ),
    (
        "Parasect",
        "Bug/Grass",
        405,
        [
            "HP: 60",
            "Attack: 95",
            "Defense: 80",
            "Sp. Atk: 60",
            "Sp. Def: 80",
            "Speed: 30",
        ],
    ),
    (
        "Venonat",
        "Bug/Poison",
        305,
        [
            "HP: 60",
            "Attack: 55",
            "Defense: 50",
            "Sp. Atk: 40",
            "Sp. Def: 55",
            "Speed: 45",
        ],
    ),
    (
        "Venomoth",
        "Bug/Poison",
        450,
        [
            "HP: 70",
            "Attack: 65",
            "Defense: 60",
            "Sp. Atk: 90",
            "Sp. Def: 75",
            "Speed: 90",
        ],
    ),
    (
        "Diglett",
        "Ground",
        265,
        [
            "HP: 10",
            "Attack: 55",
            "Defense: 25",
            "Sp. Atk: 35",
            "Sp. Def: 45",
            "Speed: 95",
        ],
    ),
    (
        "Dugtrio",
        "Ground",
        475,
        [
            "HP: 35",
            "Attack: 80",
            "Defense: 50",
            "Sp. Atk: 50",
            "Sp. Def: 70",
            "Speed: 120",
        ],
    ),
    (
        "Meowth",
        "Normal",
        290,
        [
            "HP: 40",
            "Attack: 45",
            "Defense: 40",
            "Sp. Atk: 40",
            "Sp. Def: 40",
            "Speed: 90",
        ],
    ),
    (
        "Persian",
        "Normal",
        440,
        [
            "HP: 65",
            "Attack: 70",
            "Defense: 60",
            "Sp. Atk: 65",
            "Sp. Def: 65",
            "Speed: 115",
        ],
    ),
    (
        "Psyduck",
        "Water",
        320,
        [
            "HP: 50",
            "Attack: 52",
            "Defense: 48",
            "Sp. Atk: 65",
            "Sp. Def: 50",
            "Speed: 55",
        ],
    ),
    (
        "Golduck",
        "Water",
        500,
        [
            "HP: 80",
            "Attack: 82",
            "Defense: 78",
            "Sp. Atk: 95",
            "Sp. Def: 80",
            "Speed: 85",
        ],
    ),
    (
        "Poliwag",
        "Water",
        300,
        [
            "HP: 40",
            "Attack: 50",
            "Defense: 40",
            "Sp. Atk: 40",
            "Sp. Def: 40",
            "Speed: 90",
        ],
    ),
    (
        "Poliwhirl",
        "Water",
        385,
        [
            "HP: 65",
            "Attack: 65",
            "Defense: 65",
            "Sp. Atk: 50",
            "Sp. Def: 50",
            "Speed: 90",
        ],
    ),
    (
        "Poliwrath",
        "Water/Fighting",
        510,
        [
            "HP: 90",
            "Attack: 95",
            "Defense: 95",
            "Sp. Atk: 70",
            "Sp. Def: 90",
            "Speed: 70",
        ],
    ),
    (
        "Machop",
        "Fighting",
        405,
        [
            "HP: 70",
            "Attack: 80",
            "Defense: 50",
            "Sp. Atk: 35",
            "Sp. Def: 35",
            "Speed: 35",
        ],
    ),
    (
        "Machoke",
        "Fighting",
        505,
        [
            "HP: 80",
            "Attack: 100",
            "Defense: 70",
            "Sp. Atk: 50",
            "Sp. Def: 60",
            "Speed: 45",
        ],
    ),
    (
        "Machamp",
        "Fighting",
        590,
        [
            "HP: 90",
            "Attack: 130",
            "Defense: 80",
            "Sp. Atk: 65",
            "Sp. Def: 85",
            "Speed: 55",
        ],
    ),
    (
        "Bellsprout",
        "Grass/Poison",
        300,
        [
            "HP: 50",
            "Attack: 75",
            "Defense: 35",
            "Sp. Atk: 70",
            "Sp. Def: 30",
            "Speed: 40",
        ],
    ),
    (
        "Weepinbell",
        "Grass/Poison",
        390,
        [
            "HP: 65",
            "Attack: 90",
            "Defense: 50",
            "Sp. Atk: 85",
            "Sp. Def: 45",
            "Speed: 55",
        ],
    ),
    (
        "Victreebel",
        "Grass/Poison",
        490,
        [
            "HP: 80",
            "Attack: 105",
            "Defense: 65",
            "Sp. Atk: 100",
            "Sp. Def: 70",
            "Speed: 70",
        ],
    ),
    (
        "Tentacool",
        "Water/Poison",
        335,
        [
            "HP: 40",
            "Attack: 40",
            "Defense: 35",
            "Sp. Atk: 50",
            "Sp. Def: 100",
            "Speed: 70",
        ],
    ),
    (
        "Tentacruel",
        "Water/Poison",
        515,
        [
            "HP: 80",
            "Attack: 70",
            "Defense: 65",
            "Sp. Atk: 80",
            "Sp. Def: 120",
            "Speed: 100",
        ],
    ),
    (
        "Geodude",
        "Rock/Ground",
        300,
        [
            "HP: 40",
            "Attack: 80",
            "Defense: 100",
            "Sp. Atk: 30",
            "Sp. Def: 30",
            "Speed: 20",
        ],
    ),
    (
        "Graveler",
        "Rock/Ground",
        490,
        [
            "HP: 55",
            "Attack: 95",
            "Defense: 115",
            "Sp. Atk: 45",
            "Sp. Def: 45",
            "Speed: 35",
        ],
    ),
    (
        "Golem",
        "Rock/Ground",
        590,
        [
            "HP: 80",
            "Attack: 110",
            "Defense: 130",
            "Sp. Atk: 55",
            "Sp. Def: 65",
            "Speed: 45",
        ],
    ),
    (
        "Ponyta",
        "Fire",
        410,
        [
            "HP: 50",
            "Attack: 85",
            "Defense: 55",
            "Sp. Atk: 65",
            "Sp. Def: 65",
            "Speed: 90",
        ],
    ),
    (
        "Rapidash",
        "Fire",
        500,
        [
            "HP: 65",
            "Attack: 100",
            "Defense: 70",
            "Sp. Atk: 80",
            "Sp. Def: 80",
            "Speed: 105",
        ],
    ),
    (
        "Slowpoke",
        "Water/Psychic",
        315,
        [
            "HP: 90",
            "Attack: 65",
            "Defense: 65",
            "Sp. Atk: 40",
            "Sp. Def: 40",
            "Speed: 15",
        ],
    ),
    (
        "Slowbro",
        "Water/Psychic",
        490,
        [
            "HP: 95",
            "Attack: 75",
            "Defense: 110",
            "Sp. Atk: 100",
            "Sp. Def: 80",
            "Speed: 30",
        ],
    ),
    (
        "Magnemite",
        "Electric/Steel",
        350,
        [
            "HP: 25",
            "Attack: 35",
            "Defense: 70",
            "Sp. Atk: 95",
            "Sp. Def: 55",
            "Speed: 60",
        ],
    ),
    (
        "Magneton",
        "Electric/Steel",
        495,
        [
            "HP: 50",
            "Attack: 60",
            "Defense: 95",
            "Sp. Atk: 120",
            "Sp. Def: 70",
            "Speed: 70",
        ],
    ),
    (
        "Farfetch'd",
        "Normal/Flying",
        352,
        [
            "HP: 52",
            "Attack: 65",
            "Defense: 55",
            "Sp. Atk: 58",
            "Sp. Def: 62",
            "Speed: 60",
        ],
    ),
    (
        "Doduo",
        "Normal/Flying",
        322,
        [
            "HP: 35",
            "Attack: 85",
            "Defense: 45",
            "Sp. Atk: 35",
            "Sp. Def: 35",
            "Speed: 75",
        ],
    ),
    (
        "Dodrio",
        "Normal/Flying",
        452,
        [
            "HP: 60",
            "Attack: 110",
            "Defense: 70",
            "Sp. Atk: 60",
            "Sp. Def: 60",
            "Speed: 100",
        ],
    ),
    (
        "Seel",
        "Water",
        325,
        [
            "HP: 65",
            "Attack: 45",
            "Defense: 55",
            "Sp. Atk: 40",
            "Sp. Def: 50",
            "Speed: 55",
        ],
    ),
    (
        "Dewgong",
        "Water/Ice",
        475,
        [
            "HP: 90",
            "Attack: 70",
            "Defense: 80",
            "Sp. Atk: 70",
            "Sp. Def: 95",
            "Speed: 60",
        ],
    ),
    (
        "Grimer",
        "Poison",
        390,
        [
            "HP: 80",
            "Attack: 80",
            "Defense: 50",
            "Sp. Atk: 40",
            "Sp. Def: 50",
            "Speed: 25",
        ],
    ),
    (
        "Muk",
        "Poison",
        500,
        [
            "HP: 105",
            "Attack: 105",
            "Defense: 75",
            "Sp. Atk: 65",
            "Sp. Def: 100",
            "Speed: 50",
        ],
    ),
    (
        "Shellder",
        "Water",
        305,
        [
            "HP: 30",
            "Attack: 65",
            "Defense: 100",
            "Sp. Atk: 45",
            "Sp. Def: 25",
            "Speed: 40",
        ],
    ),
    (
        "Cloyster",
        "Water/Ice",
        525,
        [
            "HP: 50",
            "Attack: 95",
            "Defense: 180",
            "Sp. Atk: 85",
            "Sp. Def: 45",
            "Speed: 70",
        ],
    ),
    (
        "Gastly",
        "Ghost/Poison",
        310,
        [
            "HP: 30",
            "Attack: 35",
            "Defense: 30",
            "Sp. Atk: 100",
            "Sp. Def: 35",
            "Speed: 80",
        ],
    ),
    (
        "Haunter",
        "Ghost/Poison",
        405,
        [
            "HP: 45",
            "Attack: 50",
            "Defense: 45",
            "Sp. Atk: 115",
            "Sp. Def: 55",
            "Speed: 95",
        ],
    ),
    (
        "Gengar",
        "Ghost/Poison",
        500,
        [
            "HP: 60",
            "Attack: 65",
            "Defense: 60",
            "Sp. Atk: 130",
            "Sp. Def: 75",
            "Speed: 110",
        ],
    ),
    (
        "Onix",
        "Rock/Ground",
        385,
        [
            "HP: 35",
            "Attack: 45",
            "Defense: 160",
            "Sp. Atk: 30",
            "Sp. Def: 45",
            "Speed: 70",
        ],
    ),
    (
        "Drowzee",
        "Psychic",
        315,
        [
            "HP: 60",
            "Attack: 48",
            "Defense: 45",
            "Sp. Atk: 43",
            "Sp. Def: 90",
            "Speed: 42",
        ],
    ),
    (
        "Hypno",
        "Psychic",
        483,
        [
            "HP: 85",
            "Attack: 73",
            "Defense: 70",
            "Sp. Atk: 73",
            "Sp. Def: 115",
            "Speed: 67",
        ],
    ),
    (
        "Krabby",
        "Water",
        325,
        [
            "HP: 30",
            "Attack: 105",
            "Defense: 90",
            "Sp. Atk: 25",
            "Sp. Def: 25",
            "Speed: 50",
        ],
    ),
    (
        "Kingler",
        "Water",
        550,
        [
            "HP: 55",
            "Attack: 130",
            "Defense: 115",
            "Sp. Atk: 50",
            "Sp. Def: 50",
            "Speed: 75",
        ],
    ),
    (
        "Voltorb",
        "Electric",
        330,
        [
            "HP: 40",
            "Attack: 30",
            "Defense: 35",
            "Sp. Atk: 55",
            "Sp. Def: 55",
            "Speed: 100",
        ],
    ),
    (
        "Electrode",
        "Electric",
        480,
        [
            "HP: 60",
            "Attack: 50",
            "Defense: 55",
            "Sp. Atk: 75",
            "Sp. Def: 70",
            "Speed: 140",
        ],
    ),
    (
        "Exeggcute",
        "Grass/Psychic",
        325,
        [
            "HP: 60",
            "Attack: 40",
            "Defense: 80",
            "Sp. Atk: 60",
            "Sp. Def: 45",
            "Speed: 40",
        ],
    ),
    (
        "Exeggutor",
        "Grass/Psychic",
        520,
        [
            "HP: 95",
            "Attack: 95",
            "Defense: 80",
            "Sp. Atk: 125",
            "Sp. Def: 65",
            "Speed: 55",
        ],
    ),
    (
        "Cubone",
        "Ground",
        320,
        [
            "HP: 50",
            "Attack: 50",
            "Defense: 95",
            "Sp. Atk: 40",
            "Sp. Def: 50",
            "Speed: 35",
        ],
    ),
    (
        "Marowak",
        "Ground",
        425,
        [
            "HP: 60",
            "Attack: 80",
            "Defense: 110",
            "Sp. Atk: 50",
            "Sp. Def: 80",
            "Speed: 45",
        ],
    ),
    (
        "Hitmonlee",
        "Fighting",
        480,
        [
            "HP: 50",
            "Attack: 120",
            "Defense: 70",
            "Sp. Atk: 35",
            "Sp. Def: 110",
            "Speed: 87",
        ],
    ),
    (
        "Hitmonchan",
        "Fighting",
        455,
        [
            "HP: 50",
            "Attack: 105",
            "Defense: 79",
            "Sp. Atk: 35",
            "Sp. Def: 110",
            "Speed: 76",
        ],
    ),
    (
        "Hitmontop",
        "Fighting",
        480,
        [
            "HP: 50",
            "Attack: 95",
            "Defense: 95",
            "Sp. Atk: 35",
            "Sp. Def: 110",
            "Speed: 70",
        ],
    ),
    (
        "Lickitung",
        "Normal",
        390,
        [
            "HP: 90",
            "Attack: 55",
            "Defense: 75",
            "Sp. Atk: 60",
            "Sp. Def: 75",
            "Speed: 30",
        ],
    ),
    (
        "Koffing",
        "Poison",
        340,
        [
            "HP: 40",
            "Attack: 65",
            "Defense: 95",
            "Sp. Atk: 60",
            "Sp. Def: 70",
            "Speed: 35",
        ],
    ),
    (
        "Weezing",
        "Poison",
        490,
        [
            "HP: 65",
            "Attack: 90",
            "Defense: 120",
            "Sp. Atk: 85",
            "Sp. Def: 70",
            "Speed: 60",
        ],
    ),
    (
        "Rhyhorn",
        "Ground/Rock",
        345,
        [
            "HP: 80",
            "Attack: 85",
            "Defense: 95",
            "Sp. Atk: 30",
            "Sp. Def: 30",
            "Speed: 25",
        ],
    ),
    (
        "Rhydon",
        "Ground/Rock",
        495,
        [
            "HP: 105",
            "Attack: 130",
            "Defense: 120",
            "Sp. Atk: 45",
            "Sp. Def: 45",
            "Speed: 40",
        ],
    ),
    (
        "Chansey",
        "Normal",
        250,
        [
            "HP: 250",
            "Attack: 5",
            "Defense: 5",
            "Sp. Atk: 35",
            "Sp. Def: 105",
            "Speed: 50",
        ],
    ),
    (
        "Tangela",
        "Grass",
        355,
        [
            "HP: 65",
            "Attack: 55",
            "Defense: 115",
            "Sp. Atk: 100",
            "Sp. Def: 40",
            "Speed: 60",
        ],
    ),
    (
        "Kangaskhan",
        "Normal",
        490,
        [
            "HP: 105",
            "Attack: 95",
            "Defense: 80",
            "Sp. Atk: 40",
            "Sp. Def: 60",
            "Speed: 90",
        ],
    ),
    (
        "Horsea",
        "Water",
        300,
        [
            "HP: 30",
            "Attack: 40",
            "Defense: 70",
            "Sp. Atk: 70",
            "Sp. Def: 25",
            "Speed: 60",
        ],
    ),
    (
        "Seadra",
        "Water",
        440,
        [
            "HP: 55",
            "Attack: 65",
            "Defense: 55",
            "Sp. Atk: 95",
            "Sp. Def: 70",
            "Speed: 85",
        ],
    ),
    (
        "Goldeen",
        "Water",
        320,
        [
            "HP: 45",
            "Attack: 67",
            "Defense: 60",
            "Sp. Atk: 35",
            "Sp. Def: 50",
            "Speed: 63",
        ],
    ),
    (
        "Seaking",
        "Water",
        450,
        [
            "HP: 65",
            "Attack: 92",
            "Defense: 65",
            "Sp. Atk: 65",
            "Sp. Def: 80",
            "Speed: 68",
        ],
    ),
    (
        "Staryu",
        "Water",
        340,
        [
            "HP: 30",
            "Attack: 45",
            "Defense: 55",
            "Sp. Atk: 70",
            "Sp. Def: 55",
            "Speed: 85",
        ],
    ),
    (
        "Starmie",
        "Water/Psychic",
        520,
        [
            "HP: 60",
            "Attack: 75",
            "Defense: 85",
            "Sp. Atk: 100",
            "Sp. Def: 85",
            "Speed: 115",
        ],
    ),
    (
        "Mr. Mime",
        "Psychic/Fairy",
        460,
        [
            "HP: 40",
            "Attack: 45",
            "Defense: 65",
            "Sp. Atk: 100",
            "Sp. Def: 120",
            "Speed: 90",
        ],
    ),
    (
        "Scyther",
        "Bug/Flying",
        500,
        [
            "HP: 70",
            "Attack: 110",
            "Defense: 80",
            "Sp. Atk: 55",
            "Sp. Def: 80",
            "Speed: 105",
        ],
    ),
    (
        "Jynx",
        "Ice/Psychic",
        455,
        [
            "HP: 65",
            "Attack: 50",
            "Defense: 35",
            "Sp. Atk: 115",
            "Sp. Def: 95",
            "Speed: 95",
        ],
    ),
    (
        "Electabuzz",
        "Electric",
        490,
        [
            "HP: 65",
            "Attack: 83",
            "Defense: 57",
            "Sp. Atk: 95",
            "Sp. Def: 85",
            "Speed: 105",
        ],
    ),
    (
        "Magmar",
        "Fire",
        495,
        [
            "HP: 65",
            "Attack: 95",
            "Defense: 57",
            "Sp. Atk: 100",
            "Sp. Def: 85",
            "Speed: 93",
        ],
    ),
    (
        "Pinsir",
        "Bug",
        500,
        [
            "HP: 65",
            "Attack: 125",
            "Defense: 100",
            "Sp. Atk: 55",
            "Sp. Def: 70",
            "Speed: 85",
        ],
    ),
    (
        "Tauros",
        "Normal",
        490,
        [
            "HP: 75",
            "Attack: 100",
            "Defense: 95",
            "Sp. Atk: 40",
            "Sp. Def: 70",
            "Speed: 110",
        ],
    ),
    (
        "Magikarp",
        "Water",
        200,
        [
            "HP: 20",
            "Attack: 10",
            "Defense: 55",
            "Sp. Atk: 15",
            "Sp. Def: 20",
            "Speed: 80",
        ],
    ),
    (
        "Gyarados",
        "Water/Flying",
        540,
        [
            "HP: 95",
            "Attack: 125",
            "Defense: 79",
            "Sp. Atk: 60",
            "Sp. Def: 100",
            "Speed: 81",
        ],
    ),
    (
        "Lapras",
        "Water/Ice",
        535,
        [
            "HP: 130",
            "Attack: 85",
            "Defense: 80",
            "Sp. Atk: 85",
            "Sp. Def: 95",
            "Speed: 60",
        ],
    ),
    (
        "Ditto",
        "Normal",
        288,
        [
            "HP: 48",
            "Attack: 48",
            "Defense: 48",
            "Sp. Atk: 48",
            "Sp. Def: 48",
            "Speed: 48",
        ],
    ),
    (
        "Eevee",
        "Normal",
        325,
        [
            "HP: 55",
            "Attack: 55",
            "Defense: 50",
            "Sp. Atk: 45",
            "Sp. Def: 65",
            "Speed: 55",
        ],
    ),
    (
        "Vaporeon",
        "Water",
        525,
        [
            "HP: 130",
            "Attack: 65",
            "Defense: 60",
            "Sp. Atk: 110",
            "Sp. Def: 95",
            "Speed: 65",
        ],
    ),
    (
        "Jolteon",
        "Electric",
        525,
        [
            "HP: 65",
            "Attack: 65",
            "Defense: 60",
            "Sp. Atk: 110",
            "Sp. Def: 95",
            "Speed: 130",
        ],
    ),
    (
        "Flareon",
        "Fire",
        525,
        [
            "HP: 65",
            "Attack: 130",
            "Defense: 60",
            "Sp. Atk: 95",
            "Sp. Def: 110",
            "Speed: 65",
        ],
    ),
    (
        "Porygon",
        "Normal",
        395,
        [
            "HP: 65",
            "Attack: 60",
            "Defense: 70",
            "Sp. Atk: 85",
            "Sp. Def: 75",
            "Speed: 40",
        ],
    ),
    (
        "Omanyte",
        "Rock/Water",
        355,
        [
            "HP: 35",
            "Attack: 40",
            "Defense: 100",
            "Sp. Atk: 90",
            "Sp. Def: 55",
            "Speed: 35",
        ],
    ),
    (
        "Omastar",
        "Rock/Water",
        495,
        [
            "HP: 70",
            "Attack: 60",
            "Defense: 125",
            "Sp. Atk: 115",
            "Sp. Def: 70",
            "Speed: 55",
        ],
    ),
    (
        "Kabuto",
        "Rock/Water",
        355,
        [
            "HP: 30",
            "Attack: 80",
            "Defense: 90",
            "Sp. Atk: 55",
            "Sp. Def: 45",
            "Speed: 55",
        ],
    ),
    (
        "Kabutops",
        "Rock/Water",
        495,
        [
            "HP: 60",
            "Attack: 115",
            "Defense: 105",
            "Sp. Atk: 65",
            "Sp. Def: 70",
            "Speed: 80",
        ],
    ),
    (
        "Aerodactyl",
        "Rock/Flying",
        515,
        [
            "HP: 80",
            "Attack: 105",
            "Defense: 65",
            "Sp. Atk: 60",
            "Sp. Def: 75",
            "Speed: 130",
        ],
    ),
    (
        "Snorlax",
        "Normal",
        540,
        [
            "HP: 160",
            "Attack: 110",
            "Defense: 65",
            "Sp. Atk: 65",
            "Sp. Def: 110",
            "Speed: 30",
        ],
    ),
    (
        "Articuno",
        "Ice/Flying",
        580,
        [
            "HP: 90",
            "Attack: 85",
            "Defense: 100",
            "Sp. Atk: 95",
            "Sp. Def: 125",
            "Speed: 85",
        ],
    ),
    (
        "Zapdos",
        "Electric/Flying",
        580,
        [
            "HP: 90",
            "Attack: 90",
            "Defense: 85",
            "Sp. Atk: 125",
            "Sp. Def: 90",
            "Speed: 100",
        ],
    ),
    (
        "Moltres",
        "Fire/Flying",
        580,
        [
            "HP: 90",
            "Attack: 100",
            "Defense: 90",
            "Sp. Atk: 125",
            "Sp. Def: 85",
            "Speed: 90",
        ],
    ),
    (
        "Dratini",
        "Dragon",
        300,
        [
            "HP: 41",
            "Attack: 64",
            "Defense: 45",
            "Sp. Atk: 50",
            "Sp. Def: 50",
            "Speed: 50",
        ],
    ),
    (
        "Dragonair",
        "Dragon",
        420,
        [
            "HP: 61",
            "Attack: 84",
            "Defense: 65",
            "Sp. Atk: 70",
            "Sp. Def: 70",
            "Speed: 70",
        ],
    ),
    (
        "Dragonite",
        "Dragon/Flying",
        600,
        [
            "HP: 91",
            "Attack: 134",
            "Defense: 95",
            "Sp. Atk: 100",
            "Sp. Def: 100",
            "Speed: 80",
        ],
    ),
    (
        "Mewtwo",
        "Psychic",
        680,
        [
            "HP: 106",
            "Attack: 110",
            "Defense: 90",
            "Sp. Atk: 154",
            "Sp. Def: 90",
            "Speed: 130",
        ],
    ),
    (
        "Mew",
        "Psychic",
        600,
        [
            "HP: 100",
            "Attack: 100",
            "Defense: 100",
            "Sp. Atk: 100",
            "Sp. Def: 100",
            "Speed: 100",
        ],
    ),
    (
        "Chikorita",
        "Grass",
        318,
        [
            "HP: 45",
            "Attack: 49",
            "Defense: 65",
            "Sp. Atk: 49",
            "Sp. Def: 65",
            "Speed: 45",
        ],
    ),
    (
        "Bayleef",
        "Grass",
        405,
        [
            "HP: 60",
            "Attack: 62",
            "Defense: 80",
            "Sp. Atk: 63",
            "Sp. Def: 80",
            "Speed: 60",
        ],
    ),
    (
        "Meganium",
        "Grass",
        525,
        [
            "HP: 80",
            "Attack: 82",
            "Defense: 100",
            "Sp. Atk: 83",
            "Sp. Def: 100",
            "Speed: 80",
        ],
    ),
    (
        "Cyndaquil",
        "Fire",
        309,
        [
            "HP: 39",
            "Attack: 52",
            "Defense: 43",
            "Sp. Atk: 60",
            "Sp. Def: 50",
            "Speed: 65",
        ],
    ),
    (
        "Quilava",
        "Fire",
        405,
        [
            "HP: 58",
            "Attack: 64",
            "Defense: 58",
            "Sp. Atk: 80",
            "Sp. Def: 65",
            "Speed: 80",
        ],
    ),
    (
        "Typhlosion",
        "Fire",
        534,
        [
            "HP: 78",
            "Attack: 84",
            "Defense: 78",
            "Sp. Atk: 109",
            "Sp. Def: 85",
            "Speed: 100",
        ],
    ),
    (
        "Totodile",
        "Water",
        314,
        [
            "HP: 50",
            "Attack: 65",
            "Defense: 64",
            "Sp. Atk: 44",
            "Sp. Def: 50",
            "Speed: 43",
        ],
    ),
    (
        "Croconaw",
        "Water",
        405,
        [
            "HP: 65",
            "Attack: 80",
            "Defense: 80",
            "Sp. Atk: 59",
            "Sp. Def: 63",
            "Speed: 58",
        ],
    ),
    (
        "Feraligatr",
        "Water",
        530,
        [
            "HP: 85",
            "Attack: 105",
            "Defense: 100",
            "Sp. Atk: 79",
            "Sp. Def: 83",
            "Speed: 78",
        ],
    ),
    (
        "Sentret",
        "Normal",
        215,
        [
            "HP: 35",
            "Attack: 46",
            "Defense: 34",
            "Sp. Atk: 35",
            "Sp. Def: 45",
            "Speed: 20",
        ],
    ),
    (
        "Furret",
        "Normal",
        415,
        [
            "HP: 85",
            "Attack: 76",
            "Defense: 64",
            "Sp. Atk: 45",
            "Sp. Def: 55",
            "Speed: 90",
        ],
    ),
    (
        "Hoothoot",
        "Normal/Flying",
        262,
        [
            "HP: 60",
            "Attack: 30",
            "Defense: 30",
            "Sp. Atk: 36",
            "Sp. Def: 56",
            "Speed: 50",
        ],
    ),
    (
        "Noctowl",
        "Normal/Flying",
        452,
        [
            "HP: 100",
            "Attack: 50",
            "Defense: 50",
            "Sp. Atk: 76",
            "Sp. Def: 96",
            "Speed: 70",
        ],
    ),
    (
        "Ledyba",
        "Bug/Flying",
        390,
        [
            "HP: 40",
            "Attack: 20",
            "Defense: 30",
            "Sp. Atk: 40",
            "Sp. Def: 80",
            "Speed: 55",
        ],
    ),
    (
        "Ledian",
        "Bug/Flying",
        490,
        [
            "HP: 55",
            "Attack: 35",
            "Defense: 50",
            "Sp. Atk: 55",
            "Sp. Def: 110",
            "Speed: 85",
        ],
    ),
    (
        "Spinarak",
        "Bug/Poison",
        315,
        [
            "HP: 40",
            "Attack: 60",
            "Defense: 50",
            "Sp. Atk: 40",
            "Sp. Def: 40",
            "Speed: 35",
        ],
    ),
    (
        "Ariados",
        "Bug/Poison",
        415,
        [
            "HP: 70",
            "Attack: 90",
            "Defense: 70",
            "Sp. Atk: 60",
            "Sp. Def: 60",
            "Speed: 40",
        ],
    ),
    (
        "Crobat",
        "Poison/Flying",
        498,
        [
            "HP: 85",
            "Attack: 90",
            "Defense: 80",
            "Sp. Atk: 70",
            "Sp. Def: 80",
            "Speed: 130",
        ],
    ),
    (
        "Chinchou",
        "Water/Electric",
        330,
        [
            "HP: 75",
            "Attack: 38",
            "Defense: 35",
            "Sp. Atk: 56",
            "Sp. Def: 56",
            "Speed: 67",
        ],
    ),
    (
        "Lanturn",
        "Water/Electric",
        460,
        [
            "HP: 125",
            "Attack: 58",
            "Defense: 58",
            "Sp. Atk: 76",
            "Sp. Def: 76",
            "Speed: 67",
        ],
    ),
    (
        "Pichu",
        "Electric",
        205,
        [
            "HP: 20",
            "Attack: 40",
            "Defense: 15",
            "Sp. Atk: 35",
            "Sp. Def: 35",
            "Speed: 60",
        ],
    ),
    (
        "Cleffa",
        "Fairy",
        250,
        [
            "HP: 50",
            "Attack: 25",
            "Defense: 28",
            "Sp. Atk: 45",
            "Sp. Def: 55",
            "Speed: 15",
        ],
    ),
    (
        "Igglybuff",
        "Normal/Fairy",
        210,
        [
            "HP: 90",
            "Attack: 30",
            "Defense: 15",
            "Sp. Atk: 40",
            "Sp. Def: 20",
            "Speed: 15",
        ],
    ),
    (
        "Togepi",
        "Fairy",
        245,
        [
            "HP: 35",
            "Attack: 20",
            "Defense: 65",
            "Sp. Atk: 40",
            "Sp. Def: 40",
            "Speed: 20",
        ],
    ),
    (
        "Togetic",
        "Fairy/Flying",
        405,
        [
            "HP: 55",
            "Attack: 40",
            "Defense: 85",
            "Sp. Atk: 80",
            "Sp. Def: 105",
            "Speed: 40",
        ],
    ),
    (
        "Natu",
        "Psychic/Flying",
        320,
        [
            "HP: 40",
            "Attack: 50",
            "Defense: 45",
            "Sp. Atk: 70",
            "Sp. Def: 50",
            "Speed: 70",
        ],
    ),
    (
        "Xatu",
        "Psychic/Flying",
        470,
        [
            "HP: 65",
            "Attack: 75",
            "Defense: 70",
            "Sp. Atk: 95",
            "Sp. Def: 70",
            "Speed: 95",
        ],
    ),
    (
        "Mareep",
        "Electric",
        280,
        [
            "HP: 55",
            "Attack: 40",
            "Defense: 40",
            "Sp. Atk: 65",
            "Sp. Def: 55",
            "Speed: 35",
        ],
    ),
    (
        "Flaaffy",
        "Electric",
        365,
        [
            "HP: 70",
            "Attack: 55",
            "Defense: 55",
            "Sp. Atk: 80",
            "Sp. Def: 60",
            "Speed: 45",
        ],
    ),
    (
        "Ampharos",
        "Electric",
        510,
        [
            "HP: 90",
            "Attack: 75",
            "Defense: 75",
            "Sp. Atk: 115",
            "Sp. Def: 90",
            "Speed: 45",
        ],
    ),
    (
        "Bellossom",
        "Grass",
        490,
        [
            "HP: 75",
            "Attack: 80",
            "Defense: 95",
            "Sp. Atk: 90",
            "Sp. Def: 100",
            "Speed: 50",
        ],
    ),
    (
        "Marill",
        "Water/Fairy",
        250,
        [
            "HP: 70",
            "Attack: 20",
            "Defense: 50",
            "Sp. Atk: 25",
            "Sp. Def: 50",
            "Speed: 40",
        ],
    ),
    (
        "Azumarill",
        "Water/Fairy",
        400,
        [
            "HP: 100",
            "Attack: 50",
            "Defense: 80",
            "Sp. Atk: 60",
            "Sp. Def: 80",
            "Speed: 50",
        ],
    ),
    (
        "Sudowoodo",
        "Rock",
        410,
        [
            "HP: 70",
            "Attack: 100",
            "Defense: 115",
            "Sp. Atk: 30",
            "Sp. Def: 65",
            "Speed: 30",
        ],
    ),
    (
        "Politoed",
        "Water",
        500,
        [
            "HP: 90",
            "Attack: 75",
            "Defense: 70",
            "Sp. Atk: 90",
            "Sp. Def: 100",
            "Speed: 70",
        ],
    ),
    (
        "Hoppip",
        "Grass/Flying",
        250,
        [
            "HP: 35",
            "Attack: 40",
            "Defense: 50",
            "Sp. Atk: 30",
            "Sp. Def: 30",
            "Speed: 50",
        ],
    ),
]

# The dataset contains various Pokémon from multiple generations along with their base stats and types.
